rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode

before_script:
  - psql -c 'create database activerecord-postgis-array_test;' -U postgres
  - cp spec/dummy/config/database.yml.example spec/dummy/config/database.yml
  - RAILS_ENV=test rake db:migrate

notifications:
  email: 
    - git@danmcclain.net
  campfire:
    rooms:
      - secure: "yVESPleawl+fzvnzXw/W7rULyCjMEq3gPc3cEqcqM2SBBtEIDNXto2zoTAoR\nC5yqhijr+UtmVMsI7CxVK3XvfkmCJZN9P4DP0uas8XYx5DsSabCdPN0h3pka\nbaDCMCInU5QF4WswL2iuyLsOJeKDRwxh09adsHi1HpMgf0nTKPA="
